### ISSUE TITLE
Problems with newer engine versions

### ISSUE THREAD

**Issue by RobinZitt** [ash3D/UEVideoRecorder#16]
Hi. Does this plugin work in Unreal Engine 4.25 or 4.26? I works for me on version 4.23, but the plugin won't build in newer versions of the engine. Is there something I can change to make it work or is this plugin just not compatible with the newer engine versions? I would appreciate an answer.

**Comment by ash3D** [comment]
@RobinZitt Hi, sorry for delay.
It turned out that recent UE versions brings some breaking changes (remove deprecated APIs and some other). But nothing critical, I just updated the plugin and it now works well with new Unreal versions (I've tested with 4.26).

Note that it still have good performance only in DX11 mode. If you want to use it with other rendering APIs then additional optimizations desirable in order to attain adequate performance in complex scenes.

**Comment by RobinZitt** [comment]
It now works perfectly for me. Thank you a lot!
